server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: authuser
    password: authpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: auth-service